### ISSUE TITLE
should we have separate folders for the programming exercises?

### ISSUE THREAD

**Issue by cschaffner** [BasicProbability/BasicProbability.github.io#10]
In the theory section, we all put it in a single folder.
@philschulz , do you expect to provide them with more files sometimes?

If we make the change, we have to adapt the links on the homepage

**Comment by philschulz** [comment]
I just like to keep things apart so as to not cram a single directory too much. I might indeed provide them with extra material at some point (depends on the exercises and the data they will involve). For assignment 2 I am actually going to do a subpart of it myself and I thought it might be helpful if I uploaded my code after they have done the assignment. Long story short: at the moment I would like to keep separate directories.
