### ISSUE TITLE
Theory assignment 3

### ISSUE THREAD

**Issue by brochhagen** [BasicProbability/BasicProbability.github.io#11]
I just uploaded a draft for next week's assignment. Feedback and additions are welcome, particularly if any of you has simple proof exercise to contribute.

**Comment by cschaffner** [comment]
We could do something along the lines of class exercise 2 and homework 3 of my IT class:
http://homepages.cwi.nl/~schaffne/courses/inftheory/2014/inf14fall-ex1.pdf

**Comment by brochhagen** [comment]
These do not match the contents of the third lesson that well. Philip and I just added a couple, but I fear the second type III exercise is too simple and should actually be type II. I think that adding another type III and switching the current type III.2 to type II would be ideal. I'll give it some more thought if no one else gets inspired in the meantime.

**Comment by philschulz** [comment]
Christian and I are planning to include on optional section on the negative binomial into the script. Maybe we can have the computation of the variance and expectation of that distribution as a (hard) second type III exercise?

**Comment by brochhagen** [comment]
That's a neat idea. Done!

**Comment by philschulz** [comment]
Hey, I just erased exercise II.5 because it was the same as II.6 anyway. So II.6 is the new II.5 now.

**Comment by cschaffner** [comment]
maybe another one from my IT course can be cast as exercise about expected values?

Tall, fat people. Suppose that the average height of people in a room is 1.5m. Suppose that the average weight is 50kg.
(a) [1 point] Argue that no more than one third of the population is 4.5m tall.
(b) [2 points] Find an upper bound on the fraction of people who are simultanously tall (say, at least 3m) and fat (say, at least 150kg).
