### ISSUE TITLE
ch4 exercises

### ISSUE THREAD

**Issue by cschaffner** [BasicProbability/BasicProbability.github.io#17]
For 2, we could ask them to sketch (and interpret) the answer as function of k (between 0..1) and c=5 and c=100 ?

**Comment by cschaffner** [comment]
In Type II, do you mean "events" instead of RVs?

Also, what do you mean by P(E1 | H) \bottom P(E2 | H) ? We have not formally defined what it means for two events to be independent when conditioned on another. I guess you mean 
P[E1 \cap E2 | H] = P[E1 | H] \* P[E2 | H] ?

**Comment by brochhagen** [comment]
On TypeI.2: Good idea

On TypeII.1:
(a) Yes, events and not RVs. Thanks for catching that, 
(b) Would P[E1 \cap E2 | H] = P[E1 | H] \* P[E2 | H]  express something different? In any case, that is what I meant so I'll adapt it accordingly.
