### ISSUE TITLE
Theory HW 5 questions

### ISSUE THREAD

**Issue by philschulz** [BasicProbability/BasicProbability.github.io#19]
I think we should maybe kick out exercise I.2 (or at least put an exclamation mark there) because in the script we explicitly avoid talking about cases where the limit does not exist.

Also the notation in II.2 is a bit unclear. What does sqrt[+] mean? Thanks a lot in advance.

**Comment by brochhagen** [comment]
Done and done! For the record sqrt[+] was meant to denote the positive square root, but I changed the notation anyway.
