### ISSUE TITLE
Exercise II.1.i

### ISSUE THREAD

**Issue by philschulz** [BasicProbability/BasicProbability.github.io#20]
Can you be more specific there? Tbh I wouldn't really know what to do there. Also, if I was a clever student I would just give 1 as an answer because 1 is an upper bound for any probability. So may this should be something like "Give an upper bound it terms of ....".

**Comment by brochhagen** [comment]
Maybe 'least upper-bound' would do the trick. Anyway, I see your more general problem and will think about ways to reformulate the exercise (the problem being that being too explicit renders (i) incredibly easy and (ii) sort-of.).
