### ISSUE TITLE
programming HW4

### ISSUE THREAD

**Issue by cschaffner** [BasicProbability/BasicProbability.github.io#33]
in the naive_bayes_classifier.py in the zipped prerequisites, in the line you have to change yourself, it says "import" twice instead of "from ... import"

**Comment by cschaffner** [comment]
typo in Naive_Bayes.py, line 16
vacubuLary

**Comment by cschaffner** [comment]
please add a line 31 to naive_bayes_classifier.py for convience
    print("Starting smoothing and normalizing at {}".format(datetime.now()))

**Comment by philschulz** [comment]
Everything corrected.
